name: 6.2 Nexmon LKM CI

permissions:
  contents: write

on:
  push:
    tags:
      - '*'

jobs:
  build-lkm:
    name: Build LKM
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      -
        name: Build
        run: |
          touch /tmp/test
          #docker build -f Dockerfile-6.2 . -t 6.2
          #docker create --name temp 6.2
          #docker cp temp:/code/linux/drivers/net/wireless/broadcom/brcm80211/brcmfmac/brcmfmac.ko ./brcmfmac.ko
      - name: Test
        run: cat Release.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            /tmp/test

