name: 6.2 Nexmon LKM CI

on:
  push:
    tags:
      - '*'

jobs:
  build-lkm:
    name: Build LKM
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      -
        name: Build and push containers
        run: |
          touch /tmp/test
          #docker build -f Dockerfile-6.2 . -t 6.2
          #docker create --name temp 6.2
          #docker cp temp:/code/linux/drivers/net/wireless/broadcom/brcm80211/brcmfmac/brcmfmac.ko ./brcmfmac.ko
      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Nexmon 6.2 RPI ${{ github.ref }}
          draft: false
          prerelease: false
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          #asset_path: ./brcmfmac.ko
          asset_path: /tmp/test
          asset_name: brcmfmac.ko
          asset_content_type: application/octet-stream
